name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  deploy:
    uses: ./.github/workflows/deployment-test.yml
    with:
      name: QS
      url: sw6.studio1-test.de

