name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  deploy:
    uses: ./.github/workflows/deployment-test.yml
    with:
      name: QS
      url: sw6.studio1-test.de
  test-env:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: print env
        run: echo ${{vars.DESCRIPTION}}
